version: "3.0"

services:
  postgres:
    image: postgres:15.2-alpine
    command: ["-c", "log_statement=all"]
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5432:5432"
