GRANT SELECT, UPDATE, INSERT ON members TO orca;
GRANT SELECT, UPDATE, INSERT ON members_files TO orca;
GRANT SELECT, UPDATE, INSERT ON occupations TO orca;
GRANT SELECT, UPDATE, INSERT ON workplaces TO orca;
