[package]
name = "orca"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
rocket = { version = "0.5.0-rc.2", features = [ "json" ] }
rocket-validation = "0.1.3"
validator = "0.16.0"
sqlx = { version = "0.6.2", features = [ "runtime-tokio-rustls", "postgres", "macros", "all-types" ] }
time = { version = "0.3.19", features = [ "serde-human-readable" ] }
rustc-serialize = "0.3.24"
tokio = { version = "1.25.0", features = [ "io-std", "fs", "process" ] }
image = "0.24.5"
hyper = { version = "0.14.24", features = [ "http1", "client", "runtime" ] }
serde_json = "1.0.93"
hyper-openssl = "0.9.2"
openssl = "0.10.45"
