[global.limits]
json = 2_097_152

[global]
# Bind to and host
address = "127.0.0.1"
host = "http://localhost:8000"

# Logging
log_level = "debug"

# Email (smtp) configuration
smtp_host = "mail.ictunion.cz"
smtp_user = "noreply@ictunion.cz"
smtp_password = ""

# Email configuration
notification_email = ""
email_sender_email = ""
email_sender_name = "ICT Union"
templates_dir = "./templates"

# Database
postgres = "postgres://orca@localhost/ictunion"
web_db_pool = 5
processing_db_pool = 2

# PDF printing
tex_exe = "xelatex"

# Authentication / Authorization
keycloak_host = "https://keycloak.ictunion.cz"
keycloak_realm = "testing-members"
keycloak_client_id = "orca"

# Business logic configuration
processing_queue_size = 16

    # Confirmation api redirect urls
    [global.verify_redirects_to]
    default = "http://localhost:1313/en/confirmed"
    cs = "http://localhost:1313/cs/schvaleno"
