[global.limits]
json = 2_097_152

[global]
# Bind to and host
address = "127.0.0.1"
host = "http://localhost:8000"

# Logging
log_level = "debug"

# API key for mandrill (mailchip transactional emails)
# Remember that this is secret!
# If this is not defined instead of sending emails we
# Just log information that email would be send (for development purposes)
# This requires info level log to be enabled (which is by default)
# mandrill_api_key = ""

# Email (mandrill) configuration
notification_email = ""
email_sender_email = "noreply@planning-game.com"
email_sender_name = "Planning Game"
email_confirmation_template = "email_confirmation"
email_new_registration_notification_template = "new_registration_notification_template"

# Database
postgres = "postgres://orca@localhost/ictunion"
web_db_pool = 5
processing_db_pool = 2

# PDF printing
tex_exe = "xelatex"

# Business logic configuration
processing_queue_size = 16
verify_redirects_to = "http://localhost:1313/registration-confirmed"

    # Confirmation api redirect urls
    [global.verify_redirects_to]
    default = "http://localhost:1313/en/confirmed"
    cs = "http://localhost:1313/cs/schvaleno"
