name: "Acceptance Test"

on:
  push:
    branches:
      - main

jobs:
  run-acceptance-test:
    runs-on: ubuntu-latest
    services:
      mailserver:
        image: rnwood/smtp4dev:v3
        ports:
          - 2525:25

      postgres:
        image: postgres:15.2-alpine
        env:
          # Enable password authentication even for local connections
          POSTGRES_USER: postgres
          POSTGRES_DB: ictunion
          POSTGRES_PASSWORD: superuser
          POSTGRES_HOST_AUTH_METHOD: "trust"
        ports:
          # maps tcp port 5432 on service container to the host
          - 5432:5432
        # Set health checks to wait until postgres has started
        # needed because the postgres container does not provide a healthcheck
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install nix
        uses: cachix/install-nix-action@v18

      - name: Run migrations
        working-directory: gray-whale
        run: |
          nix build
          cp refinery.example.toml refinery.toml
          ./result/bin/gray-whale-migrate migrate

      - name: Build and configure and run orca
        working-directory: orca
        run: |
          nix build
          cp Rocket.example.toml Rocket.toml
          ./result/bin/orca &
          sleep 5
        env:
          ROCKET_SMTP_HOST: "localhost"
          ROCKET_SMTP_USER: ""
          ROCKET_SMTP_PASSWORD: ""
          ROCKET_KEYCLOAK_HOST: "https://keycloak.ictunion.cz"
          ROCKET_KEYCLOAK_REALM: "testing-members"

      - name: Check status of orca
        run: |
          curl localhost:8000/status
