name: "Orca"

on:
  push:

jobs:
  nix-build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      # Nix
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Check orca
        run: nix flake check --log-format raw --option log-lines 100

      - name: Build via nix
        run: nix build .#orca --log-format raw
