name: "Orca"

on:
  push:

jobs:
  nix-build:
    runs-on: ubuntu-latest
    # if: github.ref_name == 'main'
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      # Nix
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build via nix
        working-directory: orca
        run: nix build
